WaylandExecutor: Fix deprecated `std::shared_ptr<T>::unique` usage.
The project asks for C++23 standard to be used[1] while
std::shared_ptr<T>::unique[2] was removed in C++20:

../src/server/frontend_wayland/wayland_executor.cpp:201:33: error: no member named 'unique' in 'std::shared_ptr<mir::frontend::WaylandExecutor::State>'
  201 |             if (!me->work_queue.unique())
      |                  ~~~~~~~~~~~~~~ ^

[1] https://github.com/canonical/mir/blob/v2.16.4/CMakeLists.txt#L61-L63
[2] https://en.cppreference.com/w/cpp/memory/shared_ptr/unique