Add missing <cstring> header for strdup
/spread/mir/src/server/frontend_xwayland/xwayland_server.cpp: In function 'void {anonymous}::exec_xwayland(const mir::frontend::XWaylandSpawner&, const string&, mir::Fd, mir::Fd, float)':
/spread/mir/src/server/frontend_xwayland/xwayland_server.cpp:79:24: error: 'strdup' was not declared in this scope
   79 |         args.push_back(strdup(std::to_string(fd).c_str()));
      |                        ^~~~~~