ConsoleServices: Add missing file_descriptor_source constructors casts
libc++ doesn't appear to do an implicit conversion from mir::Fd to int
which boost::iostreams::file_descriptor_source constructor expects.

In file included from ../src/server/console/linux_virtual_terminal.cpp:33:
/usr/include/boost/iostreams/stream.hpp:144:49: error: call to constructor of 'boost::iostreams::file_descriptor_source' is ambiguous
...
../src/server/console/linux_virtual_terminal.cpp:658:44: note: in instantiation of function template specialization 'boost::iostreams::stream<boost::iostreams::file_descriptor_source>::stream<mir::Fd, boost::iostreams::file_descriptor_flags>' requested here
  658 |             stream<file_descriptor_source> uevent{fd, file_descriptor_flags::never_close_handle};
      |                                            ^