all: Add missing headers to make libc++ happy
In file included from ../src/common/event.cpp:19:
In file included from ../src/common/handle_event_exception.h:17:
../include/common/mir/log.h:39:10: error: no type named 'exception_ptr' in namespace 'std'; did you mean 'exception'?
   39 |     std::exception_ptr const& exception,
      |     ~~~~~^~~~~~~~~~~~~
      |          exception

In file included from ../src/wayland/protocol_error.cpp:17:
../include/wayland/mir/wayland/protocol_error.h:50:17: error: implicit instantiation of undefined template 'std::basic_string<char>'
   50 |     std::string error_message;
      |                 ^

../src/server/compositor/multi_monitor_arbiter.cpp:137:17: error: no member named 'any_of' in namespace 'std'
  137 |     return std::any_of(
      |            ~~~~~^

../src/server/frontend_xwayland/xwayland_client_manager.cpp:97:32: error: use of undeclared identifier 'getuid'
   97 |             proc_stat.st_uid = getuid();
      |                                ^

In file included from ../src/miral/application_info_internal.cpp:17:
In file included from ../src/miral/application_info_internal.h:20:
In file included from ../include/miral/miral/application_info.h:20:
../include/miral/miral/application.h:37:48: error: unknown type name 'pid_t'
   37 | auto pid_of(Application const& application) -> pid_t;
      |                                                ^

(and some more similar ones)