Add missing stdexcept include to mirserverhooks
This fixes a bunch of errors like the following while building against
musl libc:

  ../src/miroil/mir_server_hooks.cpp: In member function 'std::shared_ptr<mir::scene::PromptSessionManager> miroil::MirServerHooks::the_prompt_session_manager() const':
  ../src/miroil/mir_server_hooks.cpp:164:16: error: 'logic_error' is not a member of 'std'
    164 |     throw std::logic_error("No prompt session manager available. Server not running?");
        |                ^~~~~~~~~~~