Add missing throw_exception.hpp include
Fix these errors with boost 1.71.0:

/home/pmos/build/src/mir-1.1.2/src/server/report/lttng/lttng_report_factory.cpp:67:5:
error: use of undeclared identifier 'BOOST_THROW_EXCEPTION'
    BOOST_THROW_EXCEPTION(std::logic_error("Not implemented"));
    ^
/home/pmos/build/src/mir-1.1.2/src/server/report/lttng/lttng_report_factory.cpp:77:5:
error: use of undeclared identifier 'BOOST_THROW_EXCEPTION'
    BOOST_THROW_EXCEPTION(std::logic_error("Not implemented"));