Stop forcing systemtap integration
This isn't available on Alpine (and other distros)

/usr/include/lttng/tracepoint.h:39:10: fatal error: sys/sdt.h: No such file or directory
   39 | #include <sys/sdt.h>
      |          ^~~~~~~~~~~

(cherry picked from commit 77920fb7ac5b734b696769fb25acb9e25206060d)